name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checks out repo
      uses: actions/checkout@v1
    
    - name: Setups Python.
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generates HTML documentation
      uses: synchronizing/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: Builds the PDF documentation
      uses: synchronizing/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"
        docs-folder: "docs/"

    - name: Saves the HTML build documentation
      uses: actions/upload-artifact@v2
      with:
        path: docs/build/html/

    - name: Saves the PDF build documentation
      uses: actions/upload-artifact@v2
      with:
        path: docs/build/latex/mitm.pdf
        
    - name: Commits docs changes to gh-pages branch
      run: |
        # Copies documentation outside of git folder.  
        mkdir -p ../docs/html ../docs/pdf
        cp -r docs/build/html ../docs/
        cp docs/build/latex/mitm.pdf ../docs/pdf/
        # Checks out to gh-pages branch.
        git checkout gh-pages
        # Copies files to branch.
        cp -r ../docs/html/* .
        cp ../docs/pdf/mitm.pdf .
        # Sets up no Jekyll config.
        touch .nojekyll
        # Commits the changes.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Documentation update." -a || true

    - name: Push changes to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: True
