name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checks out repo
      uses: actions/checkout@v1

    - name: Generates HTML documentation
      uses: synchronizing/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y git"
        docs-folder: "docs/"

    - name: Saves the HTML build documentation
      uses: actions/upload-artifact@v2
      with:
        path: docs/build/html/
        
    - name: Commits docs changes to gh-pages branch
      run: |
        # Copies documentation outside of git folder.  
        mkdir -p ../docs/html
        cp -r docs/build/html ../docs/
        # Checks out to gh-pages branch.
        git checkout -b gh-pages
        # Copies files to branch.
        cp -r ../docs/html/* .
        # Sets up no Jekyll config.
        touch .nojekyll
        # Commits the changes.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Documentation update." -a || true

    - name: Push changes to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: True
